package com.example.demo.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="groceries")
public class Groceries {
	@Id //primary key
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	@Column(name="id")//autogenerated 
	private int id;
	@Column(name="Gname")
	private String name;
	@Column(name="Gquantity")
	private int quantity;
	@Column(name="Gprice")
	private int price;
	public Groceries() {
		
		
	}
	public Groceries(int id, String name, int quantity, int price) {
		
		this.id = id;
		this.name = name;
		this.quantity = quantity;
		this.price = price;
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public int getPrice() {
		return price;
	}
	public void setPrice(int price) {
		this.price = price;
	}
	@Override
	public String toString() {
		return "Groceries [id=" + id + ", name=" + name + ", quantity=" + quantity + ", price=" + price + "]";
	}
}
